spring:
  application:
    name: @project.name@
    description: @project.version@
    version: @project.description@
  profiles:
    active: ${PROFILE_ENVIRONMENT:default}
    include: actuator

service:
 name:  ${spring.application.name}
 description: ${spring.application.description}