
logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            eureka: DEBUG
            discovery: DEBUG
service:
 name:  ${spring.application.name} - dev
 description: ${spring.application.description}